### PR TITLE
bootanimation: Fix build for 720

### PR DESCRIPTION
**Pull request by neobuddy89**
- Typo broke the build on 720p devices.

Change-Id: Ie47469c4909f63bb7595e43bf28d956a634cd807
Signed-off-by: Pranav Vashi neobuddy89@gmail.com

### CODE REVIEW

**Comment by Joshndroid** [comment]
Does your push further stop the other error u mention in the comments?

**Comment by neobuddy89** [comment]
Nope. 

EDIT: Haven't checked. Because have defined required new define...

**Comment by Joshndroid** [comment]
It originally occurred even while I had it defined, I then took the - operators out and ran another build to which it fixed... Could u try changing the 2 ifeq statements to this

if [[ $(TARGET_SCREEN_ASPECT_RATIO) == "16by9" ]];

And don't define the flag

**Comment by temasek** [comment]
Josh...is this good for merge?

**Comment by Joshndroid** [comment]
Yes this is just a typo fix.. I was merging before work whole running late... Got a bit derpy

**Comment by neobuddy89** [comment]
@Joshndroid Fixed the error mentioned before.
https://github.com/neobuddy89/android_vendor_cm/commit/7908c50f1ee1114beb2949e3f1cebe4d0866c53f

**Pull request merged**
