### PR TITLE
edit build name to include by.temasek

### PR DESCRIPTION
**Pull request by maxime-poulain**
Hello,

dunno if you would like to include this but this patch just add  by.temasek.

When built package name is like this : cm-12.1-20150813-UNOFFICIAL-by.temasek-shamu.zip

### CODE REVIEW

**Comment by ZdrowyGosciu** [comment]
Use device config e.g. https://github.com/temasek/android_device_samsung_hlte/commit/ea0c4877b3282bc6a5a714e28abebd4a78e40733

**Comment by maxime-poulain** [comment]
OH indeed that happens when you don't look too carefully at raw code :p,
 thx I close this !

**Comment by temasek** [comment]
I don't want it to be compulsory. That's why it isn't  for all. Those want to do it shall add it at their own device tree. :)

**Comment by ZdrowyGosciu** [comment]
I like to name build with version too ;)
Simple example of shell script :
`CMVERSION=$(grep ro.cm.version $OUT/system/build.prop | cut -d= -f2)`
`TMVERSION=$(grep temasek_version_default packages/apps/Settings/res/values/cr_strings.xml | cut -dV -f2 | cut -d"<" -f1)`
`BUILDFILE=temasek-$TMVERSION-cm-$CMVERSION`
`mv $OUT/cm-$CMVERSION.zip ./$BUILDFILE.zip`
:smile:

**Comment by Joshndroid** [comment]
ey mate will that stop me needing to manually add v-15.7 or whatever the version number is? if so, i wish to use it for my devices, trying to further automate everything i do when building this will cut some time.

**Comment by temasek** [comment]
@ZdrowyGosciu 

I like that idea to tag version of build to filename. Can u submit a pull request?

**Comment by Joshndroid** [comment]
haha just tweeted you to do this tema... AWESOME beat me to it

**Comment by temasek** [comment]
It is his idea. Let him have it :+1:

**Comment by ZdrowyGosciu** [comment]
It's from my "make OTA" script (renaming ZIP build, making OTA XML, pushing to FTP) :smiley: After build I just run ./make-ota (from base directory) and just hit ENTER :smile:
https://gist.github.com/ZdrowyGosciu/e99ca6932281b15666a8
Share & use if You like it :+1: @temasek: I don't know where to "pull" it :smile:
Best wishes !

**Comment by Joshndroid** [comment]
you could add this to the zip building phase temasek, i'm guessing you could copy and paste the necessary section in conjunction with the zip naming phase.

**Comment by ZdrowyGosciu** [comment]
:+1:

**Pull request closed without merging**
